import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')

/**
 * Hive plan 2 P6 regression: install.ps1 must carry a UTF-8 BOM.
 *
 * What we measured: Windows PowerShell 5.1 (the officially recommended execution path) decodes a .ps1
 * without a BOM using the ANSI code page (GBK on a Chinese system), so every Chinese string in the script
 * came out as mojibake -- and the mojibake bytes happened to contain quote/paren bytes -> ParserError, the script could not even start.
 * The BOM makes PS5.1 decode as UTF-8 and the problem goes away.
 */
test('install.ps1 starts with a UTF-8 BOM so Windows PowerShell 5.1 can parse it', () => {
  const bytes = readFileSync(join(root, 'install.ps1'))
  assert.deepEqual(
    [bytes[0], bytes[1], bytes[2]],
    [0xef, 0xbb, 0xbf],
    'install.ps1 must start with a UTF-8 BOM (PS5.1 gives a ParserError without one, measured)',
  )
  // Everything after the BOM must be valid UTF-8, no half-baked encoding
  assert.doesNotThrow(() => new TextDecoder('utf-8', { fatal: true }).decode(bytes))
})

/**
 * Hive plan 2 P6 regression: install.ps1 must have a codeload zip fallback.
 *
 * What we measured: on Chinese networks github.com git HTTPS times out or resets (raw times out too)
 * and only codeload.github.com is reachable (measured 200). Without the fallback a bare-metal Windows
 * install cannot complete there. The fallback leaves a working install; npm run update needs a git repo, and the script says so.
 */
test('install.ps1 falls back to codeload zip when git clone fails', () => {
  const text = new TextDecoder('utf-8', { fatal: true }).decode(readFileSync(join(root, 'install.ps1')))
  assert.match(text, /codeload\.github\.com\/litestartup-com\/hellodac\/zip\/refs\/heads\/master/)
  assert.match(text, /Expand-Archive/)
  assert.match(text, /git clone https:\/\/github\.com\/litestartup-com\/hellodac\.git/)
})

/**
 * Hive plan 2 P6 regression: install.ps1 must stop dead on setup's failure exit code.
 *
 * What we measured: setup's pnpm self-check exits 2 in red, and the old script never checked the exit
 * code -- it carried on to build, announced "done" and opened the browser: false success (the manager crashes with no config). No half-success state.
 */
test('install.ps1 aborts when npm run setup exits non-zero', () => {
  const text = new TextDecoder('utf-8', { fatal: true }).decode(readFileSync(join(root, 'install.ps1')))
  assert.match(text, /\$LASTEXITCODE -ne 0\) \{ throw 'npm run setup failed/)
})

/**
 * Hive plan 2 P6 regression: install.ps1 must not install a global pnpm -- setup pulls the node
 * dependencies on the fly with npx pnpm@9 (a global pnpm >=10 ignores the build allowlist, measured).
 */
test('install.ps1 does not install a global pnpm', () => {
  const text = new TextDecoder('utf-8', { fatal: true }).decode(readFileSync(join(root, 'install.ps1')))
  assert.doesNotMatch(text, /npm install -g pnpm'/)
})

/**
 * Hive plan 2 P6 regression: the nginx runtime default.conf is generated and must never enter git again.
 *
 * What we measured: on a live host, install.sh in TLS mode sed'd the template into the tracked
 * deploy/nginx/default.conf -> git pull forever reported modified (reported by the user on 2026-09-07).
 * The fix: the template was renamed default.conf.example (tracked), while the runtime default.conf is
 * generated by install.sh on every run and gitignored; the compose mount path is unchanged.
 */
test('nginx runtime default.conf is generated from the example, never tracked', () => {
  const installSh = readFileSync(join(root, 'install.sh'), 'utf8')
  assert.match(installSh, /cp deploy\/nginx\/default\.conf\.example deploy\/nginx\/default\.conf/, 'install.sh without a domain must generate the runtime config from the example')
  assert.match(installSh, /"deploy\/nginx\/\$SRC" > deploy\/nginx\/default\.conf/, 'install.sh with a domain must generate it from the tls-*.conf template')

  const gitignore = readFileSync(join(root, '.gitignore'), 'utf8')
  assert.match(gitignore, /^deploy\/nginx\/default\.conf$/m, 'the runtime default.conf must be gitignored (otherwise editing it on the host dirties the tree again)')

  const example = readFileSync(join(root, 'deploy/nginx/default.conf.example'), 'utf8')
  assert.match(example, /listen 80/, 'the example template must keep the HTTP form')
  assert.match(example, /location \/api\/internal\//, 'the example template must keep the H1 intranet ACL block')
  assert.match(example, /deny all/, 'the example template must keep deny all')
})

/**
 * Incident regression (ubuntu-focal went dark on 2026-09-25): join.sh must install a system-level unit.
 *
 * What we measured: the old version installed a systemd **user** unit + `systemctl --user enable --now`
 * but never ran `loginctl enable-linger` -- a user manager exists only while a login session does,
 * so after a host reboot the agent never came up at all (`systemctl --user is-enabled` said enabled,
 * while the boot log showed only other UIDs' user managers), every node was dark and only a manual start could save it.
 * Worse, each SSH login created a new root user manager, and several agents coexisting sent node.spawn
 * over and over -> EADDRINUSE. The fix = a system unit (no dependence on a login session) + cleaning up
 * the old user units.
 */
test('join.sh installs a systemd system unit, not a session-scoped user unit', () => {
  const text = readFileSync(join(root, 'public/assets/agent/join.sh'), 'utf8')
  assert.match(text, /UNIT_PATH="\/etc\/systemd\/system\/\$UNIT_NAME\.service"/, 'the unit must live in /etc/systemd/system (a system service that starts at boot)')
  assert.match(text, /WantedBy=multi-user\.target/, 'a system unit must attach to multi-user.target, or boot will not start it')
  assert.match(text, /systemctl enable --now "\$UNIT_NAME"/, 'it must enable --now the service')
  assert.doesNotMatch(text, /WantedBy=default\.target/, 'no more user units (session-scoped, dark after a reboot)')
  assert.match(text, /systemctl --user disable --now "\$\{legacy\}\.service"/, 'the old user unit must be cleaned up, or an SSH login starts another agent that fights for the port')
  assert.match(text, /KillMode=process/, 'an agent self-update restart must not take down the DSH node still doing its work')
})

