/**
 * Hive plan 2 P6: fleet.md -- the manager-generated shared topology/boundary document (the one derived truth).
 *
 * One copy per node workspace, synced automatically as the config changes; node AGENTS.md files
 * reference it, and the brain's dispatch criteria read it instead of memorising a roster. It is a generated
 * file: a content change overwrites it, and users never hand-edit it (change the topology = change manager.config.yaml / use the wizard).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'
import { homedir } from 'node:os'
import type { AppConfig } from '../config.js'
import { withCommitLock } from './commit-lock.js'

export const FLEET_FILE = 'fleet.md'
/** The brain token file (under the node user's HOME; 0600; never in the workspace or git). */
export const BRAIN_TOKEN_FILE = '.brain-auth'

export const renderFleetDoc = (config: AppConfig): string => {
  const agents = Object.values(config.agents)
  const lines: string[] = [
    '# Fleet topology and boundaries (generated by the manager — do not edit by hand)',
    '',
    'The manager generates this file from its config: network topology, the node list and the boundaries below are authoritative here.',
    'To change the topology, edit `manager.config.yaml` or add/remove nodes in the wizard; this file follows.',
    '',
    '## Key addresses (use environment variables, never hardcode)',
    '',
    '- manager internal API base: `$MANAGER_URL` (bash) / `$env:MANAGER_URL` (pwsh)',
    '- internal API auth header: `X-Brain-Token`, value in `BRAIN_TOKEN` (reference it; never print it or write it to a file)',
    '- browser entry point: the URL your users have (nginx 80/443); node ports stay on the container/host network and are never public',
    '',
    '## Nodes',
    '',
  ]
  for (const agent of agents) {
    const ep = config.endpoints[agent.endpoint]
    const runner = ep?.spawn?.runner === 'docker' ? 'container' : ep?.spawn === null ? 'external' : 'process'
    const managed = ep?.spawn?.managed === true ? 'managed' : 'external'
    const visibility = agent.public ? 'public (callable through the external API)' : 'private'
    lines.push(`- **${agent.id}** (${agent.name}): ${runner} · ${managed} · ${visibility}`)
  }
  lines.push(
    '',
    '## Boundaries (red lines, identical on every node)',
    '',
    '1. A node reads and writes **its own workspace** (this directory) only; every cross-node action goes through a manager dispatch.',
    '2. The brain is read-only towards the fleet: it observes through the internal API and always dispatches work to a worker.',
    '3. Environment variables (`BRAIN_TOKEN` / `MANAGER_URL` / `GW_KEY_*`) are referenced, never printed and never written to disk.',
    '',
  )
  return lines.join('\n')
}

/** Syncs fleet.md into every agent workspace; returns the agent ids written or updated. */
export const syncFleetDocs = async (config: AppConfig, log?: (line: string) => void): Promise<string[]> => {
  const updated: string[] = []
  const doc = renderFleetDoc(config)
  for (const agent of Object.values(config.agents)) {
    const path = join(agent.workspacePath, FLEET_FILE)
    try {
      if (readFileSync(path, 'utf8') === doc) {
        // Even when the content is unchanged, keep going into commitFleetDoc: the file may already exist but never have been committed (dirty from history)
      } else {
        mkdirSync(agent.workspacePath, { recursive: true })
        writeFileSync(path, doc, 'utf8')
        updated.push(agent.id)
      }
    } catch {
      // The file does not exist -> write it
      try {
        mkdirSync(agent.workspacePath, { recursive: true })
        writeFileSync(path, doc, 'utf8')
        updated.push(agent.id)
      } catch (error) {
        log?.(`fleet.md ${agent.id}: sync failed: ${(error as Error).message.split('\n')[0]}`)
        continue
      }
    }
    // Hive plan 2 P6: fleet.md is a manager-generated file -- syncing it commits it, so the workspace stays clean.
    // Debt H3: the commit takes the per-agent commit lock (mutually exclusive with run snapshots) and names only fleet.md.
    await commitFleetDoc(agent.workspacePath, agent.id)
  }
  return updated
}

/**
 * Commits fleet.md only (a manager-generated file); no git repo or a failed commit does not block.
 *
 * Debt H3, two fixes:
 * 1. `git commit -- fleet.md` is path-limited -- other staged changes in the user's workspace must
 *    never ride along into the manager's commit (the old implementation had no pathspec and committed the whole repo).
 * 2. It goes through `withCommitLock(agentId)` -- the same lock as the runner's snapshot commits, so
 *    two git processes no longer step on each other's index.lock.
 */
const commitFleetDoc = async (workspacePath: string, agentId: string): Promise<void> => {
  await withCommitLock(agentId, async () => {
    try {
      execFileSync('git', ['add', '--', FLEET_FILE], { cwd: workspacePath, stdio: 'ignore' })
      const staged = execFileSync('git', ['diff', '--cached', '--name-only', '--', FLEET_FILE], {
        cwd: workspacePath,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
      }).trim()
      if (staged === '') return
      execFileSync('git', ['commit', '-m', 'chore: update fleet.md (generated by the manager)', '--', FLEET_FILE], {
        cwd: workspacePath,
        stdio: 'ignore',
      })
    } catch {
      // Not a git repo (or the commit failed): the smoke check reports a dirty workspace explicitly, so no forcing it here
    }
  })
}

/**
 * The brain token file (decided 2026-09-06: it lands in the node user's HOME, never in the workspace or git).
 * The DSH tool sandbox scrubs environment variables containing TOKEN/KEY (DSH-FACTS §2), so the env route is out;
 * HOME is not on the scrub list, and skill manuals read `$HOME/.brain-auth`.
 * In container form the node entrypoint derives and writes it from an environment variable; on bare metal the manager calls this function at boot.
 */
export const provisionBrainToken = (homeDir: string = homedir(), log?: (line: string) => void): boolean => {
  const token = process.env.BRAIN_TOKEN ?? ''
  if (token === '') {
    log?.('brain token: skipped (BRAIN_TOKEN is not set)')
    return false
  }
  const path = join(homeDir, BRAIN_TOKEN_FILE)
  try {
    mkdirSync(homeDir, { recursive: true })
    let current = ''
    try {
      current = readFileSync(path, 'utf8')
    } catch {
      // The file does not exist -> first write
    }
    if (current !== token) writeFileSync(path, token, { encoding: 'utf8', mode: 0o600 })
    return true
  } catch (error) {
    log?.(`brain token: failed: ${(error as Error).message.split('\n')[0]}`)
    return false
  }
}
