/**
 * 蜂群2计划 P6：fleet.md —— manager 生成的拓扑/边界共享文档（唯一派生真相）。
 *
 * 每个节点工作区一份，随 config 变化自动同步；节点 AGENTS.md 引用它，
 * 主脑的派工判据读它而不是背死名单。文件是生成物：内容变了就覆盖，
 * 用户永远不手改它（改拓扑 = 改 manager.config.yaml / 用向导）。
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'
import { homedir } from 'node:os'
import type { AppConfig } from '../config.js'
import { withCommitLock } from './commit-lock.js'

export const FLEET_FILE = 'fleet.md'
/** 主脑令牌文件（节点用户 HOME 下；0600；不进工作区/git）。 */
export const BRAIN_TOKEN_FILE = '.brain-auth'

export const renderFleetDoc = (config: AppConfig): string => {
  const agents = Object.values(config.agents)
  const lines: string[] = [
    '# Fleet topology and boundaries (generated by the manager — do not edit by hand)',
    '',
    'The manager generates this file from its config: network topology, the node list and the boundaries below are authoritative here.',
    'To change the topology, edit `manager.config.yaml` or add/remove nodes in the wizard; this file follows.',
    '',
    '## Key addresses (use environment variables, never hardcode)',
    '',
    '- manager internal API base: `$MANAGER_URL` (bash) / `$env:MANAGER_URL` (pwsh)',
    '- internal API auth header: `X-Brain-Token`, value in `BRAIN_TOKEN` (reference it; never print it or write it to a file)',
    '- browser entry point: the URL your users have (nginx 80/443); node ports stay on the container/host network and are never public',
    '',
    '## Nodes',
    '',
  ]
  for (const agent of agents) {
    const ep = config.endpoints[agent.endpoint]
    const runner = ep?.spawn?.runner === 'docker' ? 'container' : ep?.spawn === null ? 'external' : 'process'
    const managed = ep?.spawn?.managed === true ? 'managed' : 'external'
    const visibility = agent.public ? 'public (callable through the external API)' : 'private'
    lines.push(`- **${agent.id}** (${agent.name}): ${runner} · ${managed} · ${visibility}`)
  }
  lines.push(
    '',
    '## Boundaries (red lines, identical on every node)',
    '',
    '1. A node reads and writes **its own workspace** (this directory) only; every cross-node action goes through a manager dispatch.',
    '2. The brain is read-only towards the fleet: it observes through the internal API and always dispatches work to a worker.',
    '3. Environment variables (`BRAIN_TOKEN` / `MANAGER_URL` / `GW_KEY_*`) are referenced, never printed and never written to disk.',
    '',
  )
  return lines.join('\n')
}

/** 把 fleet.md 同步进每个 agent 工作区；返回被写入/更新的 agent id。 */
export const syncFleetDocs = async (config: AppConfig, log?: (line: string) => void): Promise<string[]> => {
  const updated: string[] = []
  const doc = renderFleetDoc(config)
  for (const agent of Object.values(config.agents)) {
    const path = join(agent.workspacePath, FLEET_FILE)
    try {
      if (readFileSync(path, 'utf8') === doc) {
        // 内容没变也继续走 commitFleetDoc：文件可能已存在但未提交（历史遗留 dirty）
      } else {
        mkdirSync(agent.workspacePath, { recursive: true })
        writeFileSync(path, doc, 'utf8')
        updated.push(agent.id)
      }
    } catch {
      // 文件不存在 → 写
      try {
        mkdirSync(agent.workspacePath, { recursive: true })
        writeFileSync(path, doc, 'utf8')
        updated.push(agent.id)
      } catch (error) {
        log?.(`fleet.md ${agent.id}: sync failed: ${(error as Error).message.split('\n')[0]}`)
        continue
      }
    }
    // 蜂群2计划 P6：fleet.md 是 manager 生成物——同步即提交，工作区保持 clean。
    // 债务 H3：提交走每 agent 提交锁（与 run 快照提交互斥），且只提交 fleet.md 一个路径。
    await commitFleetDoc(agent.workspacePath, agent.id)
  }
  return updated
}

/**
 * 只提交 fleet.md（manager 生成物）；无 git 仓或提交失败不阻断。
 *
 * 债务 H3 两处修复：
 * 1. `git commit -- fleet.md` 路径限定——用户工作区里已 stage 的其它改动
 *    绝不能被捎带进 manager 的提交（旧实现无 pathspec，会整仓提交）。
 * 2. 走 `withCommitLock(agentId)`——与 runner 的快照提交同一把锁，
 *    两个 git 进程不再互相踩 index.lock。
 */
const commitFleetDoc = async (workspacePath: string, agentId: string): Promise<void> => {
  await withCommitLock(agentId, async () => {
    try {
      execFileSync('git', ['add', '--', FLEET_FILE], { cwd: workspacePath, stdio: 'ignore' })
      const staged = execFileSync('git', ['diff', '--cached', '--name-only', '--', FLEET_FILE], {
        cwd: workspacePath,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
      }).trim()
      if (staged === '') return
      execFileSync('git', ['commit', '-m', 'chore: update fleet.md (generated by the manager)', '--', FLEET_FILE], {
        cwd: workspacePath,
        stdio: 'ignore',
      })
    } catch {
      // 不是 git 仓（或提交失败）：工作区脏由 smoke 显性报告，不在这里硬处理
    }
  })
}

/**
 * 主脑令牌文件（2026-09-06 拍板：落点 = 节点用户 HOME，不进工作区/git）。
 * DSH 工具沙箱会洗掉 TOKEN/KEY 字样环境变量（DSH-FACTS §2），env 通路走不通；
 * HOME 不在清洗名单，技能手册读 `$HOME/.brain-auth`。
 * 容器形态由节点 entrypoint 从环境变量派生写入；裸机由 manager 启动时调本函数。
 */
export const provisionBrainToken = (homeDir: string = homedir(), log?: (line: string) => void): boolean => {
  const token = process.env.BRAIN_TOKEN ?? ''
  if (token === '') {
    log?.('brain token: skipped (BRAIN_TOKEN is not set)')
    return false
  }
  const path = join(homeDir, BRAIN_TOKEN_FILE)
  try {
    mkdirSync(homeDir, { recursive: true })
    let current = ''
    try {
      current = readFileSync(path, 'utf8')
    } catch {
      // 文件不存在 → 首次写入
    }
    if (current !== token) writeFileSync(path, token, { encoding: 'utf8', mode: 0o600 })
    return true
  } catch (error) {
    log?.(`brain token: failed: ${(error as Error).message.split('\n')[0]}`)
    return false
  }
}
